export const RETRIVE_USER = "RETRIVE_USER";
export const RETRIVE_USER_SUCESS = "RETRIVE_USER_SUCESS";
export const RETRIVE_TOKEN = "RETRIVE_TOKEN";
export const RETRIVE_TOKEN_SUCESS = "RETRIVE_TOKEN_SUCESS"






